"""SQLAlchemy ORM models reflecting the existing Wellstar.db tables (read-only)."""

from sqlalchemy import Column, Float, Integer, String
from sqlalchemy.orm import declarative_base

WellstarBase = declarative_base()


class Equipment(WellstarBase):
    __tablename__ = "Equipment"

    ID = Column(Integer, primary_key=True)
    Job = Column(String)
    ReportDate = Column(String)
    # Shaker screen sizes (5 shakers × 4 screens)
    ShakerSize1_1 = Column(String)
    ShakerSize1_2 = Column(Float)
    ShakerSize1_3 = Column(Float)
    ShakerSize1_4 = Column(Float)
    ShakerSize2_1 = Column(String)
    ShakerSize2_2 = Column(Float)
    ShakerSize2_3 = Column(Float)
    ShakerSize2_4 = Column(Float)
    ShakerSize3_1 = Column(String)
    ShakerSize3_2 = Column(Float)
    ShakerSize3_3 = Column(Float)
    ShakerSize3_4 = Column(Float)
    ShakerSize4_1 = Column(Float)
    ShakerSize4_2 = Column(Float)
    ShakerSize4_3 = Column(Float)
    ShakerSize4_4 = Column(Float)
    ShakerSize5_1 = Column(Float)
    ShakerSize5_2 = Column(Float)
    ShakerSize5_3 = Column(Float)
    ShakerSize5_4 = Column(Float)
    # Shaker names and hours
    ShakerName1 = Column(String)
    ShakerName2 = Column(String)
    ShakerName3 = Column(String)
    ShakerName4 = Column(String)
    ShakerName5 = Column(String)
    ShakerHours1 = Column(Float)
    ShakerHours2 = Column(Float)
    ShakerHours3 = Column(Float)
    ShakerHours4 = Column(Float)
    ShakerHours5 = Column(Float)
    # Other equipment
    Other1_Name = Column(String)
    Other1_Information = Column(String)
    Other2_Name = Column(String)
    Other2_Information = Column(String)
    # Hydrocyclones
    Desander_Size = Column(Float)
    Desander_Cones = Column(Float)
    Desilter_Size = Column(Float)
    Desilter_Cones = Column(Float)
    MudCleaner_Size = Column(Float)
    MudCleaner_Cones = Column(Float)
    DesanderName = Column(String)
    DesilterName = Column(String)
    MudCleanerName = Column(String)
    DesanderHours = Column(Float)
    DesilterHours = Column(Float)
    MudCleanerHours = Column(Float)
    # Centrifuges
    Centrifuge1_Type = Column(String)
    Centrifuge1_Hours = Column(Float)
    Centrifuge1_FeedRate = Column(Float)
    Centrifuge1Name = Column(String)
    Centrifuge2_Type = Column(String)
    Centrifuge2_Hours = Column(Float)
    Centrifuge2_FeedRate = Column(Float)
    Centrifuge2Name = Column(String)
    Centrifuge3_Type = Column(String)
    Centrifuge3_Hours = Column(Float)
    Centrifuge3_FeedRate = Column(Float)
    Centrifuge3Name = Column(String)
    # Metadata
    SSMA_TimeStamp = Column(String)


class Sample(WellstarBase):
    __tablename__ = "Sample"

    ID = Column(Integer, primary_key=True)
    Job = Column(String)
    ReportDate = Column(String)
    SampleTime = Column(String)
    SampleNumber = Column(Integer)
    UseForCalcs = Column(Integer)
    SampleFrom = Column(String)
    Flowline_Temp = Column(String)
    TVDDepth = Column(Float)
    MDDepth = Column(Float)
    # Mud weight
    Weight_UOM = Column(String)
    Weight = Column(Float)
    MudWeight_PPG = Column(Float)
    WeightMaterial_SG = Column(Float)
    # Rheology
    Funnel_Viscosity = Column(Float)
    Funnel_Viscosity_Temp = Column(Float)
    Funnel_ViscosityUOM = Column(String)
    Plastic_Viscosity = Column(Float)
    Plastic_Viscosity_Temp = Column(Float)
    Yield_Point = Column(Float)
    Gel_Strength10sec = Column(Float)
    Gel_Strength10min = Column(Float)
    Gel_Strength30min = Column(Float)
    # Dial readings
    _600_Reading = Column("600_Reading", Float)
    _300_Reading = Column("300_Reading", Float)
    _200_Reading = Column("200_Reading", Float)
    _100_Reading = Column("100_Reading", Float)
    _3_Reading = Column("3_Reading", Float)
    _6_Reading = Column("6_Reading", Float)
    # Filtration
    Filtrate_API = Column(Float)
    API_HtHP_Filtrate = Column(Float)
    API_HtHP_Filtrate_Temp = Column(String)
    API_HtHP_Filtrate_Psi = Column(Float)
    Cake_ThicknessAPI = Column(Float)
    Cake_ThicknessHTHP = Column(Float)
    # Solids
    Solids_Content_Type = Column(String)
    Solids_Content = Column(Float)
    Liquid_Content_oil = Column(Float)
    Liquid_Content_water = Column(Float)
    Sand_Content = Column(String)  # String — may contain comma decimals
    # MBT / Bentonite
    Methylene_Blue_Capacity_Type = Column(String)
    Methylene_Blue_Capacity = Column(Float)
    MudMBT_PPB = Column(Float)
    Bentonite = Column(Float)
    Bentonite_SG = Column(Float)
    Bentonite_CEC = Column(Float)
    # pH / Alkalinity
    PH_Type = Column(String)
    PH = Column(Float)
    PH_Temperature = Column(Float)
    Alkalinity_Mud = Column(Float)
    Alkalinity_FiltratePf = Column(Float)
    Alkalinity_FiltrateMf = Column(Float)
    Carbonate_Determination = Column(String)
    Carbonate_Determination_Type = Column(String)
    BiCarbonate = Column(String)
    Hydroxyl = Column(String)
    Pf = Column(Float)
    P1 = Column(Float)
    P2 = Column(Float)
    Filtrate = Column(Float)
    # Chemistry
    Chloride = Column(Float)
    CaMg = Column(Float)
    Ca = Column(Float)
    # Solids analysis
    SolidsPct_GravHigh = Column(Float)
    SolidsPct_GravLow = Column(Float)
    SolidsPct_DrillSolids = Column(Float)
    SolidsPct_Bentonite = Column(Float)
    DrillSolids_SG = Column(Float)
    DrillSolids_CEC = Column(Float)
    # PPA / Spurt
    PPASpurt_Temp = Column(Float)
    PPASpurt_PSI = Column(Float)
    PPASpurt = Column(Float)
    PPASpurtTotal = Column(Float)
    # Static shear
    StaticShear = Column(Float)
    StaticShearTemperature = Column(Float)
    StaticShearHours = Column(Float)
    # Custom fields
    N1Name = Column(String)
    N1Value = Column(Float)
    N2Name = Column(String)
    N2Value = Column(Float)
    N3Name = Column(String)
    N3Value = Column(Float)
    N4Name = Column(String)
    N4Value = Column(Float)
    # OBM fields
    Oil_Ratio = Column(Float)
    Water_Ratio = Column(Float)
    Solids_Adjusted = Column(Float)
    ChloridesWholeMud = Column(Float)
    ChloridesWaterPhase = Column(Float)
    LimeContent = Column(Float)
    ElectricalStability = Column(Float)
    TopOilSeparation = Column(String)
    Oil_SG = Column(Float)
    EDTA = Column(Float)
    Vsn = Column(Float)
    Vw = Column(Float)
    # Report usage flags
    UseForRep = Column(Integer)
    # Min/Max spec ranges
    Plastic_Viscosity_Min = Column(Float)
    Plastic_Viscosity_Max = Column(Float)
    Yield_Point_Min = Column(Float)
    Yield_Point_Max = Column(Float)
    GelStrength_10sec_Min = Column(Float)
    GelStrength_10sec_Max = Column(Float)
    GelStrength_10min_Min = Column(Float)
    GelStrength_10min_Max = Column(Float)
    Filtrate_API_Min = Column(Float)
    Filtrate_API_Max = Column(Float)
    API_HtHP_Filtrate_Min = Column(Float)
    API_HtHP_Filtrate_Max = Column(Float)
    SoildsPct_GravLow_Min = Column(Float)
    SoildsPct_GravLow_Max = Column(Float)
    pH_Min = Column(Float)
    pH_Max = Column(Float)
    pH_Range = Column(Float)
    SoildsPct_Min = Column(Float)
    SoildsPct_Max = Column(Float)
    AvgDensity = Column(Float)
    DissolvedOxygen = Column(Float)
    FilmingAmine = Column(Float)
    Actual_CaCl2_Pct = Column(Float)
    VolWtMatl = Column(Float)
    VolLGS = Column(Float)
    Soluble_NaCl = Column(Float)
    BrineDensity = Column(Float)
    # Brine fields
    NaClPct = Column(Float)
    NaCl_Conc = Column(Float)
    CaCl2_Conc = Column(Float)
    MgCl2_Conc = Column(Float)
    EDTA_CaMg = Column(Float)
    MgCl2Pct = Column(Float)
    CaIon = Column(Float)
    CaCl2_Ca = Column(Float)
    FiltrateDensity = Column(Float)
    FormatePct = Column(Float)
    # Metadata
    SSMA_TimeStamp = Column(String)


class ConcentAddLoss(WellstarBase):
    __tablename__ = "ConcentAddLoss"

    ID = Column(Integer, primary_key=True)
    Job = Column(String)
    ReportDate = Column(String)
    AddLoss = Column(String)
    ItemName = Column(String)
    Quantity = Column(Float)
    Start = Column(Float)
    Received = Column(Float)
    RepUnits = Column(String)
    Location = Column(String)
    MudWeight = Column(Float)
    SortOrder = Column(Float)
    Notes = Column(String)
    ItemType = Column(String)


class Report(WellstarBase):
    __tablename__ = "Report"

    ID = Column(Integer, primary_key=True)
    Job = Column(String)
    ReportDate = Column(String)
    ReportNumber = Column(Integer)
    ReportType = Column(String)
    PresentActivity = Column(String)
    TVDDepth = Column(Float)
    MDDepth = Column(Float)
    Remarks = Column(String)
    Engineer = Column(String)
    Engineer_Home_Address = Column(String)
    Phone = Column(String)
    ForMudCall = Column(String)
    Warehouse = Column(String)
    Operator = Column(String)
    Operator_reportfor = Column(String)
    Contractor = Column(String)
    Contractor_reportfor = Column(String)
    RigNumber = Column(String)
    CalcMethod = Column(String)
    Manhours = Column(Float)
    InvComments = Column(String)
    NOV_Notes = Column(String)
    SSMA_TimeStamp = Column(String)


class CircData(WellstarBase):
    __tablename__ = "CircData"

    ID = Column(Integer, primary_key=True)
    Job = Column(String)
    ReportDate = Column(String)
    MudVol_Hole = Column(Float)
    MudVol_HolewoPipe = Column(Float)
    MudVol_Pits = Column(Float)
    MudVol_Riser = Column(Float)
    MudVol_totalcirc = Column(Float)
    MudVol_InStorage = Column(Float)
    MudVol_InStoragePPG = Column(Float)
    MudVol_Reserve = Column(Float)
    MudVol_Premix = Column(Float)
    MudVol_Weight = Column(Float)
    MudVol_MudType = Column(String)
    WashOutFactor = Column(Float)
    # Pump A
    Pump_SizeA_Liner = Column(Float)
    Pump_SizeA_Stk = Column(Float)
    Pump_Make = Column(String)
    Assumed = Column(Float)
    BBL_STK = Column(Float)
    STK_MIN = Column(Float)
    # Pump B
    Pump_SizeB_Liner = Column(Float)
    Pump_SizeB_Stk = Column(Float)
    Pump_MakeB = Column(String)
    BBL_STKB = Column(Float)
    STK_MINB = Column(Float)
    # Pump C
    Pump_SizeC_Liner = Column(Float)
    Pump_SizeC_Stk = Column(Float)
    Pump_MakeC = Column(String)
    BBL_STKC = Column(Float)
    STK_MINC = Column(Float)
    PumpC_Riser = Column(Integer)
    # Calculated flow
    STK_Min_Total = Column(Float)
    BBL_Min = Column(Float)
    GAL_MIN = Column(Float)
    Annular_Vel_Riser = Column(Float)
    Annular_Vel_DP = Column(Float)
    Annular_Vel_DC = Column(Float)
    Pressure_PSI = Column(Float)
    Bottoms_Up = Column(Float)
    Total_Circ_Time = Column(Float)
    # Additional volumes
    MudVol_Choke = Column(Float)
    MudVol_Kill = Column(Float)
    MudVol_Booster = Column(Float)
    DuplexPump = Column(Integer)
    RodDiameter = Column(Float)
    # Temperatures
    SurfaceTemp = Column(Float)
    BottHoleTemp = Column(Float)
    TempGrad = Column(Float)
    # Hydraulics
    HBOilType = Column(String)
    HBBrineType = Column(Float)
    PumpEffB = Column(Float)
    PumpEffC = Column(Float)
    # Metadata
    SSMA_TimeStamp = Column(String)
    WashOutVolume = Column(Float)
    NoFluid = Column(Float)
    PumpPistonA = Column(Float)
    PumpPistonB = Column(Float)
    PumpPistonC = Column(Float)
